export default [
    'Uncategorized',
    'Abstract',
    'Aerial',
    'Animals',
    'Black and White',
    'Boudoir',
    'Celebrities',
    'City & Architecture',
    'Commercial',
    'Concert',
    'Family',
    'Fashion',
    'Film',
    'Fine Art',
    'Food',
    'Journalism',
    'Landscapes',
    'Macro',
    'Nature',
    'Night',
    'Nude',
    'People',
    'Performing Arts',
    'Sport',
    'Still Life',
    'Street',
    'Transportation',
    'Travel',
    'Underwater',
    'Urban Exploration',
    'Wedding'
];
